version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: flyrank_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: flyrank
      POSTGRES_PASSWORD: flyrank123
      POSTGRES_DB: flyrank_db
    ports:
      - "5432:5432"
    volumes:
      - flyrank_pgdata:/var/lib/postgresql/data

volumes:
  flyrank_pgdata:
